### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by acmpo6ou** [CW-Henry/widgets_modifiers#1]
Hi!

I'm currently learning Flutter, and I was thinking myself that converting lots of Flutter widgets into modifiers could be an amazing idea. Then I search for a package like that, and found this one. Great job! But is this library still maintained? If I contribute a PR, will it be merged?

Thanks.

**Comment by CW-Henry** [comment]
Yes absolutely. Glad you also thought about this idea and we are on the same page. I think Flutter is a great SDK that is both seamless to code and integrates cross-platform compatibility, while also allowing sufficient customization options that eases the development process.

If you have further code suggestions regarding the package, feel free to test out and add sections in the Flutter code building. Once tested, valid PR could be applied to main branch. Thanks.

**Comment by acmpo6ou** [comment]
@CW-Henry Hi! Amazing! Thanks for your quick reply :) I guess the reason this repo was last changed 2 years ago is because Flutter is pretty stable, so there aren't many modifiers to change/add.
